# Configuration for dashboard data extraction

# Layout analysis configuration
layout:
  min_region_area: 200 
  header_threshold: 0.15 
  table_width_threshold: 0.3
  chart_width_threshold: 0.2 

# Text extraction configuration
text:
  kpi_patterns:
    - "([A-Za-z\\s]+):\\s*([^\\n]+)" # Key: Value
    - "([A-Za-z\\s]+)\\s*-\\s*([^\\n]+)" # Key - Value
    - "([A-Za-z\\s]+)\\s*=\\s*([^\\n]+)" # Key = Value

# Visual element extraction configuration
visual:
  table:
    min_cell_height: 20
    min_cell_width: 40
  chart:
    types:
      - bar_chart
      - line_chart
      - pie_chart
      - scatter_plot
